### ISSUE TITLE
Make dev code installable for AWS

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#121]
Beth's code needs to be installable to overwrite the Geonode URL's for the map.

**Comment by creinkin** [comment]
Implementation is complete and ready for testing. There are two things that were accomplished:

### Cyberspatial repository integration
* The cyberspatial repository now has a branch: geonode-njcoast-docker-integration
* This branch integrates the templates that @ecaldwe1 was working on and the original 'njcoast' folder from the cyberspatial repo
* currently, this branch turns njcoast into a git submodule pointing to ecaldwe1/cyberspatial-ui repo
* The docker container can be built from the main cyberspatial repo root if desired                       

### cyberspatial-ui repo
* @ecaldwe1 's code is now integrated with geonode/geoserver backends
* the repository has an updated Dockerfile, entrypoint, and requirements.txt that allows a clone and docker build directly from this repo rather than having to clone from the cyberspatial repo
* the settings used for DB connection are pulled from the environment variables at runtime.

**Comment by creinkin** [comment]
@Omegaice, I forgot to mention that the ALLOWED_HOSTS setting is passable in a docker environment variable. Default is 'localhost' and 'django' but will pick up env setting overriding it. 

From https://github.com/GeoNode/geonode/blob/2.6.x/geonode/settings.py:
```ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', ['localhost', 'django'])```

**Comment by charlesvardeman** [comment]
Nice Job everyone! Yay!!!
