### ISSUE TITLE
Test heat map with model output

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#125]
In order for Beth to implement the heatmap, it needs to be first tested with the Matlab model. 
Use <lat, long, value> to verify output.

As we currently have not tested a full execution of the model from input parameters to output results (we have only tested with his provided dummy data), we should take Alexandros's Matlab code and, using parameters from one of the examples in https://github.com/NJCoast/nhc_examples, check that we get something out of the model that is reasonable.

This output can also be used to allow Beth to test the Leaftlet heatmap plugin code so that we can visualize the simulation results.

**Comment by Omegaice** [comment]
As we currently have not tested a full execution of the model from input parameters to output results (we have only tested with his provided dummy data), we should take Alexandros's Matlab code and, using parameters from one of the examples in https://github.com/NJCoast/nhc_examples, check that we get something out of the model that is reasonable. 

This output can also be used to allow Beth to test the Leaftlet heatmap plugin code so that we can visualize the simulation results.
