### ISSUE TITLE
Enable click events on map

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#178]
As a user
I want to be able to click a location point or polygon 
so that I can see context-specific data.

AC:
- [x] Providing metadata from the WMS
- [x] Display pop up with text when clicked on

**Comment by charlesvardeman** [comment]
I think the issue is that the default WMS support in leaflet.js is limited and doesn't support the API [GetFeatureInfo](http://docs.geoserver.org/stable/en/user/services/wms/reference.html#getfeatureinfo) requests. There are at least a couple of work-around extensions to this solve this. The first looks like a hacktastic extension to leaflet wms found in this [gist](https://gist.github.com/rclark/6908938). The second option is to use the [leaflet.wms plugin](https://github.com/heigeo/leaflet.wms) which seems to do the correct thing with respect to getting the Feature metadata. 

Related [stackoverflow](https://stackoverflow.com/questions/46268753/filter-getfeatureinfo-results-leaflet-wms-plugin) discussion.

**Comment by mkrusche** [comment]
In our meeting with Tom, it was confirmed that they would prefer a click event on point data rather than mouse over.

**Comment by Omegaice** [comment]
The code does work by click events, I believe that you are hovering over my dad's annotations which do hover events. We should create a new issue for him to change his from hover to click events.
